[env:uno_r4wifi]
platform     = renesas-ra
board        = uno_r4wifi
framework    = arduino
lib_deps     = arduino-libraries/Arduino_Modulino
monitor_speed = 115200
upload_port  = /dev/ttyACM0
monitor_port = /dev/ttyACM0

; For Portenta X8 or other dual-core boards, change board accordingly
; and update upload_port to match the MCU serial device.
